"use strict";

var tern = require("tern/lib/tern");
var infer = require("tern/lib/infer");


// helpers

var _classUniqId = 0;

function _getUniqClassId() {
    _classUniqId += 1;
    return "AbitbolClass" + _classUniqId;
}

function _isPrivate(name) {
    return name.indexOf("_") === 0;
}

function _isGetter(name) {
    return name.indexOf("get") === 0 || name.indexOf("is") === 0 || name.indexOf("has") === 0;
}

function _getterToPropertyName(name) {
    var accessorNameLength = 3;
    if (name.indexOf("is") === 0) {
        accessorNameLength = 2;
    }
    var propName = name.slice(accessorNameLength, accessorNameLength + 1).toLowerCase();
    propName += name.slice(accessorNameLength + 1, name.length);
    return  propName ;
}


// basic class definition

var defs = {

    "!name": "abitbol",

    "!define": {
        "!known_modules": {
            "abitbol": {
                "!type": "Class"
            }
        },

    },

    "Class": {
        "!type": "fn(?) -> +Class",
        "$extend": {
            "!type": "fn(properties: ?) -> !custom:abitbolExtend",
            "!effects": ["custom abitbol_extend"]
        },
        "$class": {
            "!type": "Class"
        },
        "$map": {
            "!type": "Obj"
        },
        "prototype": {}

    }

};


// plugin functions

infer.registerFunction("abitbolExtend", function(_self, args, argNodes) {
    var hidePrivate = false;  // TODO make this configurable

    var abitbolClass = new infer.Fn(_getUniqClassId(), new infer.AVal(), [], [], new infer.AVal());
    var abitbolClassPrototype = abitbolClass.getProp("prototype").getType();

    // parent class static properties
    // TODO

    // parent class properties
    var parentClassProperties = _self.getProp("prototype").getType();
    parentClassProperties.forAllProps(function(prop, val, local) {
        if (!local) return;
        if (prop == "prototype") return;
        if (_isPrivate(prop) && hidePrivate) return;

        val.propagate(abitbolClassPrototype.defProp(prop));
    });

    // new class static properties (__classvars__)
    // TODO

    // new class mixin properties (__include__)
    // TODO

    // new class properties / computed properties
    var newProperties = args[0];
    newProperties.forAllProps(function(prop, val, local) {
        if (!local) return;
        if (_isPrivate(prop) && hidePrivate) return;

        val.propagate(abitbolClassPrototype.defProp(prop));

        // autogenerated conmputed property
        if (_isGetter(prop)) {
            var propertyType = val.getType();
            var computedProperty = abitbolClassPrototype.defProp(_getterToPropertyName(prop));
            if (propertyType && propertyType.retval) {
                propertyType.retval.propagate(computedProperty);
            }
            // TODO propagate getter's doc
        }
    });

    // new class constructor
    // TODO

    // abitbol $extend
    // TODO

    // abitbol $class
    // TODO

    // abitbol $data
    // TODO

    // abitbol $map
    // TODO

    // FIXME
    _self.forAllProps(function(prop, val, local) {
        if (!local) return;
        if (prop == "prototype") return;

        val.propagate(abitbolClass.defProp(prop));
    });

    return abitbolClass;
});

tern.registerPlugin("abitbol", function(server, options) {
    server.addDefs(defs);
});

